### ISSUE TITLE
Sample Application Crash when performing Inventory

### ISSUE THREAD

**Issue by cmsdesigner** [XerumSrl/XRFID-Android-Samples#1]
The Sample application crash when performing Inventory in region : #region custom tag methods

in function  protected override void UpdateList(String tag, int count, short? rssi)

generating exception : [um.xrfid.mobile] Explicit concurrent copying GC freed 28743(1930KB) AllocSpace objects, 1(20KB) LOS objects, 49% free, 5448KB/10MB, paused 101us,45us total 31.542ms
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
Thread started: <Thread Pool> #15
Thread finished: <Thread Pool> #13
Thread finished: <Thread Pool> #7
Thread finished: <Thread Pool> #5
Thread finished: <Thread Pool> #15
Le thread 0xd s'est arrêté avec le code 0 (0x0).
Le thread 0x7 s'est arrêté avec le code 0 (0x0).
Le thread 0x5 s'est arrêté avec le code 0 (0x0).
Le thread 0xf s'est arrêté avec le code 0 (0x0).
Thread started:  #16
Thread started: <Thread Pool> #17
Thread started: <Thread Pool> #18
[monodroid-assembly] open_from_bundles: failed to load assembly XRFID.Sample.Common.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xerum.XFramework.Common.dll
Loaded assembly: /data/data/com.xerum.xrfid.mobile/files/.__override__/XRFID.Sample.Common.dll
Loaded assembly: /data/data/com.xerum.xrfid.mobile/files/.__override__/Xerum.XFramework.Common.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Web.HttpUtility.dll
Loaded assembly: /data/data/com.xerum.xrfid.mobile/files/.__override__/System.Web.HttpUtility.dll [External]
[DpmTcmClient] RegisterTcmMonitor from: $Proxy2
[TrafficStats] tagSocket(116) with statsTag=0xffffffff, statsUid=-1

_****System.InvalidCastException:** 'Specified cast is not valid.'**_

Regards

**Comment by RubenFasola** [comment]
this repository is currently unmaintained, can you try to reproduce the issue with the application from [XRFID-Demo](https://github.com/XerumSrl/XRFID-Demo)?

if the problem still persists, open an issue on the XRFID-Demo repository with the device model and steps to reproduce

**Comment by cmsdesigner** [comment]
Hi
Thank you for your response i will check this soon 

Regards

**Comment by cmsdesigner** [comment]
Hi Ruben thank you for this greet Demo , i have tried your new repo the
client work well even if i have not de syncfusion licence but i have error
when launching the server part i had  Error: Error: Circuit host not
initialized. log @ blazor.server.js:1 to solve this problem i changed
_framework with ~framwork the same for _content to ~content

Thank you man for this greet demo
Excuse my bad english

Best Regards

Moujahed Hassan


Le mar. 27 févr. 2024 à 09:48, RubenFasola ***@***.***> a
écrit :
